server:
  port: 9000
  eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  cloud:
    gateway:
      routes[0]:
        id: inventory-service
        uri: http://localhost:8111
        predicates[0]: Path=/rest/api/inventory/**

      routes[1]:
        id: order-service
        uri: http:localhost:8082
        predicates[0]: Path=/rest/api/order/**

    main:
      web-application-type: reactive




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


