server:
  port: 9000

spring:
  application:
    name: gateaway
  cloud:
    gateway:
      routes:
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/rest/api/inventory/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/rest/api/order/**

