server:
  port: 9000


spring:
    main:
      web-application-type: reactive

    cloud:
      gateway:
        routes:
          - id: inventory-service
            uri: http://localhost:8111
            predicates:
              - Path=/rest/api/inventory/**
              -
          - id: order-service
            uri: http://localhost:8082
            predicates:
              - Path=/rest/api/order/**




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


