server:
  port: 8121

#bu benim default yml dosyam fakat eğer farklı ortamlar tercih edersem bu sefer ortam gerekliliklerine göre benim
#configurasyonumu sağlamam gerekiyor örneğin db bilgileri port bilgileri vs. ama biz default olana ortak alanları yazıp
#diğer ortamlarada gerekli olanları sadece yazarsak işimizi daha esnek yaparız
#ortama göre çalıştırmak(run) için mvn spring-boot:run -Dspring-boot.run.profiles=dev örenğin bu şekilde
#veya jar dosyası bir diğer seçenekte application.yml dosyamıza active profilimizi yazıp direk run edebiliriz.
#
spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27018
      username: rootuser2
      password: rootpass2
      database: springboot_mongo
