server:
  port: 8084

spring:
  application:
    name: orchestrator

  jpa:
    properties:
      hibernate:
        default_schema: stockservice
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"
