server:
  port: 8084

spring:
  application:
    name: orchestrator

  jpa:
    properties:
      hibernate:
        default_schema: kafka-orchestrator

  kafka:
    consumer:
      group-id: orchestrator-group
