server:
  port: 8083

spring:
  application:
    name: payment

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      username: postgres
      password: 12345

  jpa:
    properties:
      hibernate:
        default_schema: kafka-payment
